language: shell
dist: xenial
os: linux

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - ARTIFACTORY_URL=https://rpmb.jfrog.io
    - BINTRAY_REPO=php73custom
    - OS7=7.9.2009
    - OS8=8.3.2011
    - OS7TAG=7.9.2009
    - OS8TAG=8.3.2011
  jobs:
    - BUILD_COMPOSE_FILE=docker-compose.yml       BASE=centos7php73base BUILD=centos7php73    UPLOADER=centos7bintray
    - BUILD_COMPOSE_FILE=docker-compose.yml       BASE=centos7php73base BUILD=centos7php73rel UPLOADER=centos7bintray
    - BUILD_COMPOSE_FILE=docker-compose.el8.yml   BASE=centos8php73base BUILD=centos8php73    UPLOADER=centos8bintray
    - BUILD_COMPOSE_FILE=docker-compose.el8.yml   BASE=centos8php73base BUILD=centos8php73rel UPLOADER=centos8bintray

install:
  - docker-compose -f docker-compose.base.yml build --no-cache --pull ${BASE}

before_script:
  - docker-compose -f ${BUILD_COMPOSE_FILE} build --no-cache ${BUILD}

script:
  - docker-compose -f ${BUILD_COMPOSE_FILE} up --exit-code-from ${BUILD} ${BUILD}

before_deploy:
  - docker-compose -f rpmbuild/docker-compose.bintray.yml pull ${UPLOADER}

deploy:
  provider: script
  script: docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm -e BINTRAY_USER=$BINTRAY_USER -e BINTRAY_API_KEY=$BINTRAY_API_KEY -e BINTRAY_REPO=$BINTRAY_REPO -e ARTIFACTORY_URL=$ARTIFACTORY_URL ${UPLOADER}

jobs:
  include:
    - stage: build
      install: skip
      before_script: skip
      script:
        - docker-compose -f build/docker-compose.yml build --no-cache --pull
      after_success:
        - OS7TAG=7 docker-compose -f build/docker-compose.yml build
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        - provider: script
          script: docker-compose -f build/docker-compose.yml push
        - provider: script
          script: OS7TAG=7 docker-compose -f build/docker-compose.yml push
    - stage: build
      install: skip
      before_script: skip
      script:
        - docker-compose -f build/docker-compose.el8.yml build --no-cache --pull
      after_success:
        - OS8TAG=8 docker-compose -f build/docker-compose.el8.yml build
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        - provider: script
          script: docker-compose -f build/docker-compose.el8.yml push
        - provider: script
          script: OS8TAG=8 docker-compose -f build/docker-compose.el8.yml push
    - stage: runtime
      install: skip
      before_script: skip
      script:
        - docker-compose -f run/docker-compose.yml build --no-cache --pull
      after_success:
        - OS7TAG=7 docker-compose -f run/docker-compose.yml build
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        - provider: script
          script: docker-compose -f run/docker-compose.yml push
        - provider: script
          script: OS7TAG=7 docker-compose -f run/docker-compose.yml push
    - stage: runtime
      install: skip
      before_script: skip
      script:
        - docker-compose -f run/docker-compose.el8.yml build --no-cache --pull
      after_success:
        - OS8TAG=8 docker-compose -f run/docker-compose.el8.yml build
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        - provider: script
          script: docker-compose -f run/docker-compose.el8.yml push
        - provider: script
          script: OS8TAG=8 docker-compose -f run/docker-compose.el8.yml push
    - stage: dev
      install: skip
      before_script: skip
      script:
        - docker-compose -f run/docker-compose.dev.yml build --no-cache --pull
      after_success:
        - OS7TAG=7 OS8TAG=8 docker-compose -f run/docker-compose.dev.yml build
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        - provider: script
          script: docker-compose -f run/docker-compose.dev.yml push
        - provider: script
          script: OS7TAG=7 OS8TAG=8 docker-compose -f run/docker-compose.dev.yml push

stages:
  - test
  - build
  - runtime
  - dev