version: "3.5"
services:
  centos7php73base:
    networks:
      - buildnet
    build:
      context: .
      dockerfile: Dockerfile.base
      network: buildnet
    image: aursu/php73build:7-base

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7

networks:
  buildnet:
    external: true
    name: buildnet
