version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    environment:
      BINTRAY_REPO: php73custom
      PACKAGE_VCS_URL: https://github.com/aursu/rpmbuild-php-7.3
    steps:
      - checkout
      - run:
          name: Git submodules sync
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Pull images for RPM build docker services
          command: |
            docker-compose -f rpmbuild/docker-compose.yml pull
            docker-compose -f rpmbuild/docker-compose.bintray.yml pull
            docker-compose -f rpmbuild/docker-compose.refresh.yml pull
      - run:
          name: Start docker services for rpmbuild
          command: docker-compose -f rpmbuild/docker-compose.yml up -d
          background: true
          no_output_timeout: 2h
      - run:
          name: Build PHP Docker images
          command: |
            docker-compose -f docker-compose.base.yml build
            docker-compose build --no-cache
      - run:
          name: Build PHP 7.3 RPM packages
          command: docker-compose up
      - run:
          name: Upload RPM packages into Bintray
          command: |
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos7bintray
      - run:
          name: refresh repositories
          command: docker-compose -f rpmbuild/docker-compose.refresh.yml run --rm centos7refresh
      - run:
          name: Build PHP build Docker images
          command: |
            docker-compose -f build/docker-compose.yml build --no-cache --pull
            docker-compose -f run/docker-compose.yml build --no-cache --pull
            docker-compose -f run/docker-compose.dev.yml build --no-cache
      - run:
          name: Upload PHP build Docker images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push aursu/php73build:7-build
            docker push aursu/php73build:7-build-rel
            docker push aursu/php73build:7-runtime
            docker push aursu/php73build:7-dev
