version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.0.2

workflows:
  php73build:
    jobs:
      - docker-rpmbuild/rpmbuild:
          name: centos7php73
          base_service: centos7php73base
          build_service: centos7php73
          bintray_uploader: centos7bintray
      - docker-rpmbuild/rpmbuild:
          name: centos7php73rel
          base_service: centos7php73base
          build_service: centos7php73rel
          bintray_uploader: centos7bintray
      - docker-rpmbuild/rpmbuild:
          name: centos8php73
          base_service: centos8php73base
          build_file: docker-compose.el8.yml
          build_service: centos8php73
          bintray_uploader: centos8bintray
      - docker-rpmbuild/rpmbuild:
          name: centos8php73rel
          base_service: centos8php73base
          build_file: docker-compose.el8.yml
          build_service: centos8php73rel
          bintray_uploader: centos8bintray
      - docker-rpmbuild/image:
          name: centos7php73build
          build_service: centos7php73build
          requires:
            - centos7php73
      - docker-rpmbuild/image:
          name: centos7php73buildrel
          build_service: centos7php73buildrel
          requires:
            - centos7php73rel
      - docker-rpmbuild/image:
          name: centos8php73build
          compose_file: build/docker-compose.el8.yml
          build_service: centos8php73build
          requires:
            - centos8php73
      - docker-rpmbuild/image:
          name: centos8php73buildrel
          compose_file: build/docker-compose.el8.yml
          build_service: centos8php73buildrel
          requires:
            - centos8php73rel
      - docker-rpmbuild/image:
          name: centos7php73run
          compose_file: run/docker-compose.yml
          build_service: centos7php73run
          requires:
            - centos7php73
      - docker-rpmbuild/image:
          name: centos7php73devbase
          compose_file: run/docker-compose.yml
          build_service: centos7php73devbase
          requires:
            - centos7php73
      - docker-rpmbuild/image:
          name: centos8php73run
          compose_file: run/docker-compose.el8.yml
          build_service: centos8php73run
          requires:
            - centos8php73
      - docker-rpmbuild/image:
          name: centos8php73devbase
          compose_file: run/docker-compose.el8.yml
          build_service: centos8php73devbase
          requires:
            - centos8php73
      - docker-rpmbuild/image:
          name: centos7php73dev
          compose_file: run/docker-compose.dev.yml
          build_service: centos7php73dev
          requires:
            - centos7php73devbase
      - docker-rpmbuild/image:
          name: centos8php73dev
          compose_file: run/docker-compose.dev.yml
          build_service: centos8php73dev
          requires:
            - centos8php73devbase