version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    environment:
      PHP_VERSION: 7.3.0-1
      BINTRAY_REPO: php73custom
      PACKAGE_VCS_URL: https://github.com/aursu/rpmbuild-php-7.3
    steps:
      - run:
          name: Upgrade Docker CE
          command: |
            sudo apt-get update
            sudo apt-get install docker-ce=18.03.1~ce-0~ubuntu
      - run:
          name: Upgrade Docker Compose
          command: |
            sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Create Build User/Group
          command: |
            if getent group centos; then
              sudo groupmod -o -g 48 centos
            else
              sudo groupadd -o -g 48 centos
            fi

            if getent passwd centos; then
              sudo usermod -o -u 48 -g centos centos
            else
              sudo useradd -o -u 48 -g centos -M -d /var/www/html centos
            fi
      - checkout
      - run:
          name: Git submodules sync
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Start docker services for rpmbuild
          command: |
            docker-compose -f rpmbuild/docker-compose.yml pull
            docker-compose -f rpmbuild/docker-compose.yml up -d
          background: true
          no_output_timeout: 2h
      - restore_cache:
          keys:
            - rpm-cache-{{ checksum "requirements.txt" }}-{{ checksum "SPECS/php7.spec" }}
            - rpm-cache-{{ checksum "requirements.txt" }}
            - rpm-cache-
      - run:
          name: Restore Repository
          command: |
            sleep 30
            if [ -d ~/el7/RPMS ]; then
              sudo chown -R centos:centos ~/el7/RPMS
              docker cp -a ~/el7/RPMS rpmbuild_webrepo_1:/home/centos-7/rpmbuild/
            fi
      - run:
          name: Build PHP Docker images
          command: |
            docker-compose build --no-cache
      - run:
          name: Build PHP 7.3 RPM packages
          command: |
            docker run -ti --rm --net buildnet -u root aursu/rpmbuild:7-build yum -q list --disablerepo=* --enablerepo custom php-devel | grep -q $PHP_VERSION ||
              docker-compose up centos7php73
            docker run -ti --rm --net buildnet -u root aursu/rpmbuild:7-build yum -q list --disablerepo=* --enablerepo custom php7-devel | grep -q $PHP_VERSION ||
              docker-compose up centos7php73rel
      - run:
          name: Copy RPM packages
          command: |
            sudo rm -rf ~/el7
            mkdir -p ~/el7
            docker cp rpmbuild_webrepo_1:/home/centos-7/rpmbuild/RPMS ~/el7/
            sudo chown -R centos:centos ~/el7/RPMS
      - save_cache:
          key: rpm-cache-{{ checksum "requirements.txt" }}-{{ checksum "SPECS/php7.spec" }}
          paths:
            - ~/el7/RPMS
      - run:
          name: Upload RPM packages into Bintray
          command: |
            docker-compose -f rpmbuild/docker-compose.bintray.yml pull
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos7bintray
      - run:
          name: Build PHP Docker build images
          command: |
            sleep 30
            docker-compose -f docker-compose.build.yml build --no-cache
            docker push aursu/php73build:7-build
            docker push aursu/php73build:7-build-rel
