version: "3.5"
services:
  centos8php73run:
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        centos: $OS8
    image: aursu/php73build:${OS8TAG}-runtime
  centos8php73devbase:
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        centos: $OS8
        image: nodedev
    image: aursu/php73build:${OS8TAG}-devbase
  centos8php73dev2base:
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        centos: $OS8
        image: node16dev
    image: aursu/php73build:${OS8TAG}-dev2base