version: "3.5"
services:
  centos8php73run:
    build:
      context: .
      dockerfile: Dockerfile.el8
    image: aursu/php73build:8-runtime
  centos8php73devbase:
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        image: 8-nodedev
    image: aursu/php73build:8-devbase
