version: "3.5"
services:
  centos7php73dev:
    build:
      context: dev
      args:
        centos: $OS7
    image: aursu/php73build:${OS7TAG}-dev
  centos8php73dev:
    build:
      context: dev
      args:
        centos: $OS8
    image: aursu/php73build:${OS8TAG}-dev
  centos7php73dev2:
    build:
      context: dev
      args:
        centos: $OS7
        image: dev2base
    image: aursu/php73build:${OS7TAG}-dev2
  centos8php73dev2:
    build:
      context: dev
      args:
        centos: $OS8
        image: dev2base
    image: aursu/php73build:${OS8TAG}-dev2