version: "3.5"
services:
  centos7php73run:
    build:
      context: .
      args:
        centos: $OS7
    image: aursu/php73build:${OS7TAG}-runtime
  centos7php73devbase:
    build:
      context: .
      args:
        centos: $OS7
        image: nodedev
    image: aursu/php73build:${OS7TAG}-devbase
  centos7php73dev2base:
    build:
      context: .
      args:
        centos: $OS7
        image: node16dev
    image: aursu/php73build:${OS7TAG}-dev2base