version: "3.5"
services:
  centos7php73run:
    build:
      context: .
      args:
        centos: $OS7
    image: "aursu/php73build:${OS7TAG}-runtime"
  centos7php73devbase:
    build:
      context: .
      args:
        image: nodedev
        centos: $OS7
    image: "aursu/php73build:${OS7TAG}-devbase"
