version: "3.5"
services:
  centos8php73run:
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        centos: $OS8
    image: aursu/php73build:${OS8TAG}-runtime
  centos8php73devbase:
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        image: nodedev
        centos: $OS8
    image: aursu/php73build:${OS8TAG}-devbase
