version: "3.5"
services:
  centos7php73dev:
    build:
      context: dev
    image: aursu/php73build:7-dev
  centos8php73dev:
    build:
      context: dev
      args:
        image: 8-devbase
    image: aursu/php73build:8-dev